name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Gp-Connect-Appointments-Management-Fhir-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    apigee_deployments:
      - environment: internal-dev
        jinja_templates:
          GP_CONNECT_ENDPOINTS: gp-connect-prescriptions-management-fhir-endpoints-pr-${{ variables.pr_number }}
          GP_CONNECT_CONFIG: gp-connect-prescriptions-management-fhir-config
          GP_CONNECT_CONFIG_ENCRYPTED: gp-connect-prescriptions-management-fhir-config-encrypted
        post_deploy:
          - template: ./templates/post-deploy.yml
            parameters:
              is_ptl: true
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        jinja_templates:
          GP_CONNECT_ENDPOINTS: just-dummy-value-for-successful-build
          GP_CONNECT_CONFIG: just-dummy-value-for-successful-build
          GP_CONNECT_CONFIG_ENCRYPTED: just-dummy-value-for-successful-build
        post_deploy:
          - template: ./templates/post-deploy.yml
            parameters:
              is_ptl: true
