# This is an OpenAPI Specification (https://swagger.io/specification/)
# for gp-connect-appointments-management-fhir owned by NHS Digital (https://digital.nhs.uk/)
openapi: '3.0.0'
info:
  title: 'gp-connect-appointments-management-fhir'
  version: 'Computed and injected at build time by `scripts/set_version.py`'
  description: |
    ## Overview

    Use this API to book and manage patient appointments at their GP practice.

    You can:
     - retrieve a patient’s appointments
     - search for free slots
     - read an appointment
     - book an appointment
     - cancel an appointment

    You cannot:
     - amend a patient's appointments
     - re-schedule a patient's appointments (This must be done by cancelling and re-booking)

    The end user must be a patient who is:
     - registered with the GP practice
     - registered with NHS login to P9

    ## For Example:

    A patient can add, remove or retrive their appointments

    ## Who can use this API

    This API can be used by developers of clinical systems that support clinicians delivering direct care. It is a patient-facing API.

    ## Prerequisites

    Information governance (IG)

    You must:

    be compliant with the GP Connect Direct Care API Information Governance Model
    manage access to your system locally using local role-based access control (RBAC). This does not need to be compliant with the national RBAC model and GP Connect products do not require smartcards to control access, though they can be used if already implementedbe using the GP Connect APIs for direct care purposes for NHS patients in England

    Clinical safety

    You must:

    - have a clinical safety officer (CSO) who is responsible for DCB0129 and, if necessary, DCB0160. For more on clinical risk management, visit Clinical risk management standards.

    If you are confident that you can meet the prerequisites, contact us to express your interest. See 'Onboarding' below.

    ## Related APIs

      The following APIs are related to this API:

      - GP Connect access record API - retrieve a patient's medical record from the GP practice systems.
      - GP Connect prescriptions management API - manage a patient's prescriptions as held by the GP practice systems
      - GP Connect User Permissions API - manage a patient's permissions to access the medical record and services they can access at their GP practice.

    ## API status and roadmap

    This API (v1.0) is in [development, alpha](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses).

    ## Service level

    This API is a silver service, meaning it is operational 24 x 7 x 365 but only supported during business hours (8am to 6pm), Monday to Friday excluding bank holidays.

    For more details, see service levels.

    ## Technology

    This API is a FHIR API.

    It sends a FHIR STU3 payload over a Spine Server Proxy (SSP) transport.

    For more details, see FHIR.

    ## Network access

    This API is available on the internet.

    For more details, see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation

    ### Security

    This API is [user-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis), meaning an end user must be present and authenticated to use it.

    ## The end user must be:

    - a patient

    - authenticated with NHS login to P9

    The API uses Open ID Connect to authenticate the end user and OAuth 2.0 to authorise the calling system. It supports the following security pattern using NHS login:
    
    - [User-restricted RESTful APIs - NHS login separate authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-separate-authentication-and-authorisation)
        

    ## Environments and testing

    | Environment   |URL    |\n|---|---|\n|Internet-facing demonstrator   | [https://orange.testlab.nhs.uk/](https://orange.testlab.nhs.uk/)  |\n| Opentest environment  |  [https://orange.testlab.nhs.uk/opentest.html](https://orange.testlab.nhs.uk/opentest.html) |\n| Integration (INT)\t  |Provided during onboarding process   |


    ## Onboarding

    ## Expressing an interest

    If you meet the prerequisites and have a product that can integrate with GP Connect, you should express an interest with us by submitting a use case.

    The main purpose of the use case is to help us understand how you plan to use GP Connect APIs and the business issue you are looking to address. You should email your use case to us at gpconnect@nhs.net.

    Your use case should include the following information as a minimum:

    - the business problem you are intending to solve using GP wConnect
    - how GP Connect will be used in practice to benefit patients and staff
    - which of the GP Connect products you will use to benefit patients and staff
    - any end user organisations you are currently working with
    - who your clinical safety officer is and, where available, your clinical risk management process documentation
    - Once we receive your use case, we'll respond within 14 days.

    ## Consumer assurance process

    Once we approve your use case, we support you through the assurance process to go live. We will discuss the assurance process and artefacts with you to help you understand our requirements.

    ## Consumer assurance process with 4 gates

    Start your development work within 6 months of use case approval. If you miss this date, a review or new submission of the use case will be required. Changes or additional development will also require a review or new use case submission.

  contact:
    name: 'gp-connect-appointments-management-fhir API Support'
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/gp-connect-appointments-management-fhir'
    description: Sandbox environment.
  - url: 'https://int.api.service.nhs.uk/gp-connect-appointments-management-fhir'
    description: Integration test environment.
  - url: 'https://api.service.nhs.uk/gp-connect-appointments-management-fhir'
    description: Production environment.
paths: {}
components:
  schemas: {}
